name: KTX Seat Tracker

on:
  schedule:
    # UTC 기준 (15분마다 감시하고 싶을 때: '*/15 * * * *')
    # 아래 설정은 30분마다 자동 실행하도록 설정 예시
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  track:
    runs-on: ubuntu-latest
    steps:
      - name: 저장소 코드 불러오기
        uses: actions/checkout@v4

      - name: 파이썬 환경 설정
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 라이브러리 설치
        run: |
          pip install requests korail2

      - name: KTX 스크립트 실행
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py
